In [15]:
import torch
import numpy as np

In [5]:
def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape/size: {}".format(x.shape))
    print("Values: \n{}".format(x))


In [6]:
describe(torch.Tensor(2,3))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
describe(torch.rand(3,3))

Type: torch.FloatTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[0.2230, 0.4976, 0.6244],
        [0.1407, 0.2002, 0.8327],
        [0.3801, 0.6883, 0.2893]])


In [8]:
describe(torch.ones(1))

Type: torch.FloatTensor
Shape/size: torch.Size([1])
Values: 
tensor([1.])


In [31]:
X = torch.zeros(4,4)
describe(X)

Type: torch.FloatTensor
Shape/size: torch.Size([4, 4])
Values: 
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [32]:
X.fill_(5)

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])

In [33]:
describe(X)

Type: torch.FloatTensor
Shape/size: torch.Size([4, 4])
Values: 
tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])


In [34]:
npy_arr = np.random.rand(3,4)
describe(torch.from_numpy(npy_arr))

Type: torch.DoubleTensor
Shape/size: torch.Size([3, 4])
Values: 
tensor([[0.3212, 0.7687, 0.9539, 0.8021],
        [0.7139, 0.9326, 0.6661, 0.9424],
        [0.8350, 0.0590, 0.1158, 0.1638]], dtype=torch.float64)


In [35]:
X = X.long()
describe(X)

Type: torch.LongTensor
Shape/size: torch.Size([4, 4])
Values: 
tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])


In [36]:
X.add(X)

tensor([[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]])

In [37]:
X

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])

In [38]:
X.add_(X)

tensor([[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]])

In [39]:
describe(X)

Type: torch.LongTensor
Shape/size: torch.Size([4, 4])
Values: 
tensor([[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]])


In [44]:
X = torch.rand(4,4)
describe(X)
indeces = torch.LongTensor([0,2])
describe(X.index_select(dim=1, index=indeces))

Type: torch.FloatTensor
Shape/size: torch.Size([4, 4])
Values: 
tensor([[0.4585, 0.3013, 0.7134, 0.7328],
        [0.2468, 0.2843, 0.1135, 0.4352],
        [0.5591, 0.6337, 0.4613, 0.3998],
        [0.6619, 0.5526, 0.4864, 0.4647]])
Type: torch.FloatTensor
Shape/size: torch.Size([4, 2])
Values: 
tensor([[0.4585, 0.7134],
        [0.2468, 0.1135],
        [0.5591, 0.4613],
        [0.6619, 0.4864]])


In [46]:
describe(X[[1,3],[0,2]])

Type: torch.FloatTensor
Shape/size: torch.Size([2])
Values: 
tensor([0.2468, 0.4864])


In [47]:
describe(torch.cat([X,X], dim=0))

Type: torch.FloatTensor
Shape/size: torch.Size([8, 4])
Values: 
tensor([[0.4585, 0.3013, 0.7134, 0.7328],
        [0.2468, 0.2843, 0.1135, 0.4352],
        [0.5591, 0.6337, 0.4613, 0.3998],
        [0.6619, 0.5526, 0.4864, 0.4647],
        [0.4585, 0.3013, 0.7134, 0.7328],
        [0.2468, 0.2843, 0.1135, 0.4352],
        [0.5591, 0.6337, 0.4613, 0.3998],
        [0.6619, 0.5526, 0.4864, 0.4647]])


In [48]:
describe(torch.cat([X,X], dim=1))

Type: torch.FloatTensor
Shape/size: torch.Size([4, 8])
Values: 
tensor([[0.4585, 0.3013, 0.7134, 0.7328, 0.4585, 0.3013, 0.7134, 0.7328],
        [0.2468, 0.2843, 0.1135, 0.4352, 0.2468, 0.2843, 0.1135, 0.4352],
        [0.5591, 0.6337, 0.4613, 0.3998, 0.5591, 0.6337, 0.4613, 0.3998],
        [0.6619, 0.5526, 0.4864, 0.4647, 0.6619, 0.5526, 0.4864, 0.4647]])


In [50]:
describe(torch.stack([X,X], dim=0))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 4, 4])
Values: 
tensor([[[0.4585, 0.3013, 0.7134, 0.7328],
         [0.2468, 0.2843, 0.1135, 0.4352],
         [0.5591, 0.6337, 0.4613, 0.3998],
         [0.6619, 0.5526, 0.4864, 0.4647]],

        [[0.4585, 0.3013, 0.7134, 0.7328],
         [0.2468, 0.2843, 0.1135, 0.4352],
         [0.5591, 0.6337, 0.4613, 0.3998],
         [0.6619, 0.5526, 0.4864, 0.4647]]])


In [52]:
describe(torch.stack([X,X], dim=-1))

Type: torch.FloatTensor
Shape/size: torch.Size([4, 4, 2])
Values: 
tensor([[[0.4585, 0.4585],
         [0.3013, 0.3013],
         [0.7134, 0.7134],
         [0.7328, 0.7328]],

        [[0.2468, 0.2468],
         [0.2843, 0.2843],
         [0.1135, 0.1135],
         [0.4352, 0.4352]],

        [[0.5591, 0.5591],
         [0.6337, 0.6337],
         [0.4613, 0.4613],
         [0.3998, 0.3998]],

        [[0.6619, 0.6619],
         [0.5526, 0.5526],
         [0.4864, 0.4864],
         [0.4647, 0.4647]]])


In [55]:
x2 = torch.ones(3,3)
x2[:, 1] += 1
describe(x2)

Type: torch.FloatTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[1., 2., 1.],
        [1., 2., 1.],
        [1., 2., 1.]])


In [56]:
torch.cuda.is_available()

True

In [59]:
device=torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [61]:
x3 = torch.ones(3,3).to(device)
describe(x3)

Type: torch.cuda.FloatTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


In [63]:
describe(torch.rand(3,3).unsqueeze(0))

Type: torch.FloatTensor
Shape/size: torch.Size([1, 3, 3])
Values: 
tensor([[[0.7434, 0.0871, 0.7258],
         [0.1761, 0.9086, 0.9831],
         [0.4869, 0.8068, 0.0278]]])


In [64]:
describe(torch.rand(3,3).unsqueeze(1))

Type: torch.FloatTensor
Shape/size: torch.Size([3, 1, 3])
Values: 
tensor([[[0.2066, 0.7161, 0.7494]],

        [[0.8819, 0.7476, 0.2757]],

        [[0.2399, 0.7500, 0.7002]]])


In [65]:
describe(torch.rand(3,1,3).squeeze(1))

Type: torch.FloatTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[0.2601, 0.8018, 0.0319],
        [0.9402, 0.6333, 0.4285],
        [0.1560, 0.0051, 0.4544]])


In [66]:
describe(torch.nonzero(torch.rand(3,3).unsqueeze(1)))

Type: torch.LongTensor
Shape/size: torch.Size([9, 3])
Values: 
tensor([[0, 0, 0],
        [0, 0, 1],
        [0, 0, 2],
        [1, 0, 0],
        [1, 0, 1],
        [1, 0, 2],
        [2, 0, 0],
        [2, 0, 1],
        [2, 0, 2]])


In [69]:
torch.bmm(torch.rand(3,4,5), torch.rand(3,5,4)) #baatch matrix multiplication

tensor([[[0.7332, 1.4398, 1.4554, 1.5704],
         [0.6896, 0.9189, 0.9328, 0.5451],
         [1.1155, 1.1269, 1.6505, 1.5712],
         [0.5632, 1.4065, 1.1653, 1.1523]],

        [[2.4719, 1.1287, 1.1582, 2.4607],
         [2.2123, 1.0695, 1.1937, 2.1155],
         [0.9888, 0.8624, 0.8388, 1.0708],
         [1.5408, 0.8933, 0.9366, 1.5755]],

        [[1.5297, 1.4420, 0.6457, 0.6469],
         [0.6691, 0.7633, 0.4576, 0.4797],
         [1.5247, 1.1911, 0.9501, 0.9280],
         [1.7648, 1.5603, 1.0617, 1.2420]]])

In [78]:
a = torch.rand(3,1)
a

tensor([[0.3152],
        [0.9534],
        [0.0460]])

In [79]:
a.expand(3,4)

tensor([[0.3152, 0.3152, 0.3152, 0.3152],
        [0.9534, 0.9534, 0.9534, 0.9534],
        [0.0460, 0.0460, 0.0460, 0.0460]])

In [81]:
a = torch.rand(3,4,5)
a

tensor([[[0.1410, 0.5186, 0.2427, 0.2520, 0.4199],
         [0.1857, 0.7716, 0.3774, 0.4470, 0.0336],
         [0.6317, 0.9594, 0.7915, 0.7598, 0.5691],
         [0.3397, 0.7091, 0.6732, 0.3941, 0.2765]],

        [[0.9202, 0.1289, 0.6579, 0.3061, 0.1608],
         [0.6291, 0.5432, 0.9539, 0.2004, 0.2810],
         [0.9733, 0.5054, 0.9686, 0.6228, 0.8171],
         [0.1588, 0.8631, 0.0339, 0.3167, 0.9205]],

        [[0.1206, 0.6956, 0.0281, 0.6132, 0.6217],
         [0.5740, 0.3881, 0.5802, 0.5047, 0.1339],
         [0.2441, 0.4169, 0.5146, 0.4848, 0.3182],
         [0.1967, 0.9623, 0.3712, 0.7175, 0.8750]]])

In [86]:
b = torch.rand(5,4)
describe(b)

Type: torch.FloatTensor
Shape/size: torch.Size([5, 4])
Values: 
tensor([[0.3532, 0.7941, 0.8981, 0.3257],
        [0.1403, 0.4191, 0.4804, 0.3779],
        [0.7730, 0.9995, 0.7120, 0.0107],
        [0.7899, 0.0383, 0.3969, 0.3182],
        [0.2849, 0.3831, 0.9830, 0.9556]])


In [91]:
describe(b.unsqueeze(0).expand(3,5,4))

Type: torch.FloatTensor
Shape/size: torch.Size([3, 5, 4])
Values: 
tensor([[[0.3532, 0.7941, 0.8981, 0.3257],
         [0.1403, 0.4191, 0.4804, 0.3779],
         [0.7730, 0.9995, 0.7120, 0.0107],
         [0.7899, 0.0383, 0.3969, 0.3182],
         [0.2849, 0.3831, 0.9830, 0.9556]],

        [[0.3532, 0.7941, 0.8981, 0.3257],
         [0.1403, 0.4191, 0.4804, 0.3779],
         [0.7730, 0.9995, 0.7120, 0.0107],
         [0.7899, 0.0383, 0.3969, 0.3182],
         [0.2849, 0.3831, 0.9830, 0.9556]],

        [[0.3532, 0.7941, 0.8981, 0.3257],
         [0.1403, 0.4191, 0.4804, 0.3779],
         [0.7730, 0.9995, 0.7120, 0.0107],
         [0.7899, 0.0383, 0.3969, 0.3182],
         [0.2849, 0.3831, 0.9830, 0.9556]]])


[5, 4]